### PR TITLE
test: add better file comparisons

### PR DESCRIPTION
**Pull request by lrm25**

### CODE REVIEW

**Review by anodelman — CHANGES_REQUESTED** [review]
I see a lot of use of create_test_file - with uses an assert.  In some places it is wrapped in a run call (run create_test_file) which would result in the assert being eaten.  In my own code, if I have a multiline function then I ensure that it only uses exits/returns instead of asserts - then I use run/assert at the top level.  Let's go for that pattern here.  Same for copy_file_locally & move_file_locally.  

In this way, run/assert should only show up in bats test files.  Utilities and other code should use return/exit.

I know that we've had some confusion around this and I've had to do a review on my own bats testing code.  Thanks for rolling with the changes as we both get to an understanding as to how run/assert/exit all interact.

**Comment by lrm25** [comment]
> I see a lot of use of create_test_file - which uses an assert. In some places it is wrapped in a run call (run create_test_file) which would result in the assert being eaten. In my own code, if I have a multiline function then I ensure that it only uses exits/returns instead of asserts - then I use run/assert at the top level. Let's go for that pattern here. Same for copy_file_locally & move_file_locally.
> 
> In this way, run/assert should only show up in bats test files. Utilities and other code should use return/exit.
> 
> I know that we've had some confusion around this and I've had to do a review on my own bats testing code. Thanks for rolling with the changes as we both get to an understanding as to how run/assert/exit all interact.

So, just to clarify, use run/assert at the top level in all of the tests?  That's the pattern we want to go with?

**Comment by anodelman** [comment]
Right - everything that is a multiline function uses return/exit and then have the runs at the top level.  That also makes a division between test code (that uses bats-ism) and utility code (that uses bash-isms).

**Review by anodelman — CHANGES_REQUESTED** [review]
There's a lot of ' || fail "message" ' in the test files - I think that those should be run/asserts since they are at the top level.

**Comment by lrm25** [comment]
> There's a lot of ' || fail "message" ' in the test files - I think that those should be run/asserts since they are at the top level.

Should those all be changed now, or gradually over the following commits?

**Review by anodelman — APPROVED** [review]
Looks good

**Pull request merged**
